package cz.jbenak.ncrm_backend.controler;

import cz.jbenak.ncrm_backend.model.dto.ai.AiDtos;
import cz.jbenak.ncrm_backend.model.dto.marketing.CampaignDto;
import cz.jbenak.ncrm_backend.model.dto.marketing.CampaignRequest;
import cz.jbenak.ncrm_backend.services.CampaignService;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.http.HttpStatus;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.UUID;

/**
 * @author Jan Benák
 * @version 1.0
 * @since 2026-07-11
 * REST API for creating and sending marketing e-mail campaigns. Restricted to the owner
 * (and administrators); the content can be generated by AI or uploaded from a file.
 */
@RestController
@RequestMapping("/api/campaigns")
@RequiredArgsConstructor
@PreAuthorize("hasAnyRole('ADMIN', 'OWNER')")
public class CampaignController {

    private final CampaignService campaignService;

    @GetMapping
    public List<CampaignDto> findAll() {
        return campaignService.findAll();
    }

    /**
     * Generic search endpoint. Accepts repeatable {@code filter} query parameters in the form
     * {@code field:operator:value} (operators: contains, notContains, eq, neq, lt, gt, between;
     * for between the value is {@code lower,upper}). All filters are combined with AND.
     * Example: {@code /api/campaigns/search?filter=name:contains:akce&filter=status:eq:SENT}
     */
    @GetMapping("/search")
    public Page<CampaignDto> search(@RequestParam(required = false) List<String> filter, Pageable pageable) {
        return campaignService.search(filter, pageable);
    }

    @GetMapping("/{id}")
    public CampaignDto findById(@PathVariable UUID id) {
        return campaignService.findById(id);
    }

    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
    public CampaignDto create(@Valid @RequestBody CampaignRequest request, Authentication authentication) {
        return campaignService.create(request, authentication == null ? null : authentication.getName());
    }

    /**
     * Generates the campaign body using the integrated AI (Claude or ChatGPT).
     */
    @PostMapping("/generate-content")
    public AiDtos.ChatResponse generateContent(@Valid @RequestBody AiDtos.ContentGenerationRequest request) {
        return campaignService.generateContent(request);
    }

    /**
     * Extracts the campaign body from an uploaded file (plain text, HTML or PDF).
     */
    @PostMapping("/upload-content")
    public String uploadContent(@RequestParam("file") MultipartFile file) {
        return campaignService.extractContentFromFile(file);
    }

    @PostMapping("/{id}/send")
    public CampaignDto send(@PathVariable UUID id) {
        return campaignService.send(id);
    }

    @PostMapping("/{id}/cancel")
    @ResponseStatus(HttpStatus.NO_CONTENT)
    public void cancel(@PathVariable UUID id) {
        campaignService.cancel(id);
    }
}
