package cz.jbenak.ncrm_backend.model.dto.marketing;

import cz.jbenak.ncrm_backend.model.entity.marketing.CampaignEntity;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

/**
 * @author Jan Benák
 * @version 1.0
 * @since 2026-07-11
 * Request DTO for creating or updating a marketing campaign. The body can be written manually,
 * generated by AI or uploaded from a file (in that case the frontend sends the extracted content here).
 */
public record CampaignRequest(
        @NotBlank String name,
        @NotBlank String subject,
        @NotBlank String body,
        CampaignEntity.ContentSource contentSource,
        UUID companyId,
        LocalDateTime scheduledAt,
        @NotEmpty List<UUID> customerIds
) {
}
