package cz.jbenak.ncrm_backend.model.entity.marketing;

import cz.jbenak.ncrm_backend.model.entity.AuditableEntity;
import cz.jbenak.ncrm_backend.model.entity.security.UserEntity;
import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.SuperBuilder;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * @author Jan Benák
 * @version 1.0
 * @since 2026-07-11
 * Represents a marketing e-mail campaign sent to customers. The content of the campaign can be created
 * manually, generated by the integrated AI (Claude / ChatGPT) or uploaded from a file.
 * The lifecycle of the campaign is tracked via {@link CampaignStatus}.
 */

@Getter
@Setter
@ToString
@SuperBuilder
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "campaigns")
public class CampaignEntity extends AuditableEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private UUID id;

    @Column(name = "name", nullable = false)
    private String name;

    // Subject of the campaign e-mail.
    @Column(name = "subject", nullable = false)
    private String subject;

    // HTML (or plain text) body of the campaign e-mail. Stored as "text" in PostgreSQL.
    @Column(name = "body", nullable = false, length = Integer.MAX_VALUE)
    private String body;

    // How the content of the campaign was created.
    @Enumerated(EnumType.STRING)
    @Column(name = "content_source", nullable = false, length = 20)
    private ContentSource contentSource;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    @Builder.Default
    private CampaignStatus status = CampaignStatus.DRAFT;

    // User (owner or marketing specialist) who created the campaign.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by_id")
    @ToString.Exclude
    private UserEntity createdBy;

    @Column(name = "scheduled_at")
    private LocalDateTime scheduledAt;

    @Column(name = "sent_at")
    private LocalDateTime sentAt;

    @OneToMany(mappedBy = "campaign", cascade = CascadeType.ALL, orphanRemoval = true)
    @ToString.Exclude
    @Builder.Default
    private List<CampaignRecipientEntity> recipients = new ArrayList<>();

    /**
     * Convenience method keeping both sides of the campaign-recipient relation in sync.
     */
    public void addRecipient(CampaignRecipientEntity recipient) {
        recipient.setCampaign(this);
        recipients.add(recipient);
    }

    public enum CampaignStatus {
        DRAFT, SCHEDULED, SENDING, SENT, CANCELLED
    }

    public enum ContentSource {
        MANUAL, AI_GENERATED, FILE_UPLOAD
    }
}
