DB_URL: jdbc:postgresql://localhost:5432/nCRM
DB_USERNAME: ncrm
DB_PASSWORD: nCRM123
DB_SCHEMA: ncrmbo

LOCAL_USER_PASSWORD: test

#MAIL_HOST: smtp-164960.m60.wedos.net
#MAIL_PORT: 578
#MAIL_USERNAME: 'info@teza-papir.cz'
#MAIL_PASSWORD: 'Radotin.1234'
#MAIL_SMTP_AUTH: true
#MAIL_SMTP_STARTTLS_ENABLE: true