package cz.jbenak.ncrm_backend.services;

import cz.jbenak.ncrm_backend.ai.AiService;
import cz.jbenak.ncrm_backend.model.dto.ai.AiDtos;
import cz.jbenak.ncrm_backend.model.dto.marketing.CampaignDto;
import cz.jbenak.ncrm_backend.model.dto.marketing.CampaignRequest;
import cz.jbenak.ncrm_backend.model.entity.company.CompanyEntity;
import cz.jbenak.ncrm_backend.model.entity.customer.CustomerEntity;
import cz.jbenak.ncrm_backend.model.entity.marketing.CampaignEntity;
import cz.jbenak.ncrm_backend.model.entity.marketing.CampaignRecipientEntity;
import cz.jbenak.ncrm_backend.model.mapper.CampaignMapper;
import cz.jbenak.ncrm_backend.repository.CampaignRepository;
import cz.jbenak.ncrm_backend.repository.CompanyRepository;
import cz.jbenak.ncrm_backend.repository.CustomerRepository;
import cz.jbenak.ncrm_backend.repository.UserRepository;
import cz.jbenak.ncrm_backend.search.SearchSpecificationBuilder;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.ai.document.Document;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.ai.reader.pdf.PagePdfDocumentReader;
import org.springframework.core.io.ByteArrayResource;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.List;
import java.util.Set;
import java.util.UUID;
import java.util.stream.Collectors;

/**
 * @author Jan Benák
 * @version 1.0
 * @since 2026-07-11
 * Service for creating and sending marketing e-mail campaigns to customers. The content can be
 * written manually, generated by the integrated AI (Claude / ChatGPT) or uploaded from a file
 * (plain text, HTML, or PDF).
 */
@Slf4j
@Service
@RequiredArgsConstructor
@Transactional
public class CampaignService {

    /** Attribute paths of the campaign entity that can be used by the generic search API. */
    private static final Set<String> SEARCHABLE_FIELDS = Set.of(
            "name", "subject", "contentSource", "status", "scheduledAt", "sentAt",
            "company.id", "company.name", "createdBy.username");

    private final CampaignRepository campaignRepository;
    private final CompanyRepository companyRepository;
    private final CustomerRepository customerRepository;
    private final UserRepository userRepository;
    private final CampaignMapper campaignMapper;
    private final AiService aiService;
    private final JavaMailSender mailSender;

    @Transactional(readOnly = true)
    public List<CampaignDto> findAll() {
        return campaignMapper.toDtoList(campaignRepository.findAll());
    }

    /**
     * Generic search over campaigns. Filters are raw {@code field:operator:value} expressions,
     * combined with a logical AND; see {@link SearchSpecificationBuilder}.
     */
    @Transactional(readOnly = true)
    public Page<CampaignDto> search(List<String> filters, Pageable pageable) {
        log.debug("Searching campaigns with filters {}", filters);
        return campaignRepository.findAll(SearchSpecificationBuilder.build(filters, SEARCHABLE_FIELDS), pageable)
                .map(campaignMapper::toDto);
    }

    @Transactional(readOnly = true)
    public CampaignDto findById(UUID id) {
        return campaignMapper.toDto(getCampaign(id));
    }

    /**
     * Creates a campaign draft; recipients are resolved from the given customer ids
     * and their e-mail addresses are snapshotted.
     */
    public CampaignDto create(CampaignRequest request, String createdByUsername) {
        CampaignEntity campaign = CampaignEntity.builder()
                .name(request.name())
                .subject(request.subject())
                .body(request.body())
                .contentSource(request.contentSource() == null ? CampaignEntity.ContentSource.MANUAL : request.contentSource())
                .scheduledAt(request.scheduledAt())
                .company(resolveCompany(request.companyId()))
                .build();
        if (createdByUsername != null) {
            userRepository.findByUsername(createdByUsername).ifPresent(campaign::setCreatedBy);
        }
        for (UUID customerId : request.customerIds()) {
            CustomerEntity customer = customerRepository.findById(customerId)
                    .orElseThrow(() -> new NotFoundException("Customer", customerId));
            if (customer.getEmail() == null || customer.getEmail().isBlank()) {
                log.warn("Customer {} has no e-mail address, skipping as campaign recipient", customer.getName());
                continue;
            }
            campaign.addRecipient(CampaignRecipientEntity.builder()
                    .customer(customer)
                    .email(customer.getEmail())
                    .build());
        }
        if (campaign.getRecipients().isEmpty()) {
            throw new IllegalArgumentException("Campaign has no recipients with a valid e-mail address");
        }
        return campaignMapper.toDto(campaignRepository.save(campaign));
    }

    /**
     * Generates the campaign body using the integrated AI (Claude or ChatGPT).
     */
    public AiDtos.ChatResponse generateContent(AiDtos.ContentGenerationRequest request) {
        return aiService.generateContent(request);
    }

    /**
     * Extracts the campaign body from an uploaded file (plain text, HTML, or PDF).
     */
    public String extractContentFromFile(MultipartFile file) {
        String originalFilename = file.getOriginalFilename();
        String filename = originalFilename == null ? "" : originalFilename.toLowerCase();
        try {
            if (filename.endsWith(".pdf")) {
                PagePdfDocumentReader reader = new PagePdfDocumentReader(new ByteArrayResource(file.getBytes()));
                return reader.get().stream().map(Document::getText).collect(Collectors.joining("\n"));
            }
            return new String(file.getBytes(), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new IllegalArgumentException("Unable to read the uploaded file: " + e.getMessage(), e);
        }
    }

    /**
     * Sends the campaign to all pending recipients via e-mail and updates the delivery statuses.
     */
    public CampaignDto send(UUID id) {
        CampaignEntity campaign = getCampaign(id);
        if (campaign.getStatus() == CampaignEntity.CampaignStatus.SENT) {
            throw new IllegalStateException("Campaign has already been sent");
        }
        campaign.setStatus(CampaignEntity.CampaignStatus.SENDING);
        for (CampaignRecipientEntity recipient : campaign.getRecipients()) {
            if (recipient.getDeliveryStatus() == CampaignRecipientEntity.DeliveryStatus.SENT) {
                continue;
            }
            try {
                var message = mailSender.createMimeMessage();
                MimeMessageHelper helper = new MimeMessageHelper(message, "UTF-8");
                helper.setTo(recipient.getEmail());
                helper.setSubject(campaign.getSubject());
                helper.setText(campaign.getBody(), true);
                mailSender.send(message);
                recipient.setDeliveryStatus(CampaignRecipientEntity.DeliveryStatus.SENT);
                recipient.setSentAt(LocalDateTime.now(ZoneId.systemDefault()));
                recipient.setErrorMessage(null);
            } catch (Exception e) {
                log.error("Failed to send campaign e-mail to {}", recipient.getEmail(), e);
                recipient.setDeliveryStatus(CampaignRecipientEntity.DeliveryStatus.FAILED);
                recipient.setErrorMessage(e.getMessage());
            }
        }
        campaign.setStatus(CampaignEntity.CampaignStatus.SENT);
        campaign.setSentAt(LocalDateTime.now(ZoneId.systemDefault()));
        return campaignMapper.toDto(campaignRepository.save(campaign));
    }

    public void cancel(UUID id) {
        CampaignEntity campaign = getCampaign(id);
        campaign.setStatus(CampaignEntity.CampaignStatus.CANCELLED);
        campaignRepository.save(campaign);
    }

    private CampaignEntity getCampaign(UUID id) {
        return campaignRepository.findById(id).orElseThrow(() -> new NotFoundException("Campaign", id));
    }

    /**
     * Resolves the own company sending the campaign: the explicitly requested one when given,
     * otherwise the default company (may be null when no default company is defined).
     */
    private CompanyEntity resolveCompany(UUID companyId) {
        if (companyId != null) {
            return companyRepository.findById(companyId)
                    .orElseThrow(() -> new NotFoundException("Company", companyId));
        }
        return companyRepository.findByDefaultCompanyTrueAndDeletedFalse().orElse(null);
    }
}
